"""empty message

Revision ID: 972471ff4985
Revises: df6b07be920e
Create Date: 2023-07-04 00:21:09.893705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972471ff4985'
down_revision = 'df6b07be920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
